test: &default

  # Credentials for REST APIs
  client_id: AUFatNe002lH8GhdazB0eKvVo0r97uhztN-SSy0J82UFCcZInAVDknG2zoXCG9ZVw-6F9wWdd45bpLHE
  client_secret: EBdo9xyU8Mr8Ey9iPrDr2cr0VXhr6-Xu1tayZwhefcI3gerTzVwrTax-3a67Q7P3WPkILBTw7LJIT2W-

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: misterydotio-facilitator_api1.gmail.com
  password: ND955TKCJB4VKQ9D
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AT8gcXtopxxKJxmXafchzWpyqGqU
  sandbox_email_address: misterydotio-facilitator@gmail.com

development:
  <<: *default

production:
  <<: *default
  mode: live
